controller_names:
  - arm_joint_trajectory_controller
  - gripper_controller


arm_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - link_1_joint
    - link_2_joint
    - link_3_joint
    - link_4_joint
    - link_5_joint
    - link_6_joint

gripper_controller:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints: 
    - right_finger_joint

