controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_position_controller:
      type: forward_command_controller/ForwardCommandController
     
          
arm_joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_4_joint
      - link_5_joint
      - link_6_joint
    state_publish_rate: 10.0
    action_monitor_rate: 10.0
    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

gripper_position_controller:
  ros__parameters:
    joints: 
      - right_finger_joint
    interface_name: position

    
